CREATE TABLE `customer_staff` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `group_id` BIGINT(20) DEFAULT NULL COMMENT 'GRP ID',
    `staff_name` VARCHAR(45) NOT NULL COMMENT 'STAFF NAME',
    `nickname` VARCHAR(45) NOT NULL COMMENT 'NICK NAME',
    `account_id` BIGINT(20) NOT NULL COMMENT 'ACCOUNT ID',
    `system_id` BIGINT(20) DEFAULT NULL COMMENT 'IF EXIST, CURRENT STAFF FROM OUT SYSTEM',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'AVATAR',
    `phone` VARCHAR(11) DEFAULT NULL COMMENT 'PHONE NUMBER',
    `gender` VARCHAR(32) NOT NULL COMMENT 'GENDER MALE,FEMALE',
    `good_at` VARCHAR(255) DEFAULT NULL COMMENT 'COME ON',
    `is_auto_reply` TINYINT(1) DEFAULT '0' COMMENT 'SHOULD AUTO REPLAY',
    `welcome_message` VARCHAR(255) DEFAULT NULL COMMENT 'WELCOME MESSAGE',
    `status` VARCHAR(32) NOT NULL COMMENT 'STATUS: ONLINE, OFFLINE',
    `remark` VARCHAR(255) DEFAULT NULL COMMENT 'REMARK',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '1=DELETED, 0=NOT DELETED',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED TIME',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED TIME',
    -- KEYS
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CUSTOMER STAFF';

CREATE TABLE `customer_group` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `group_name` VARCHAR(45) NOT NULL COMMENT 'GROUP NAME',
    `group_description` VARCHAR(200) DEFAULT NULL COMMENT 'GROUP DESC',
        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED TIME',
        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED TIME',
    -- KEYS
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CUSTOMER STAFF GROUP';

CREATE TABLE `outsourcing_system` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `system_name` VARCHAR(45) NOT NULL COMMENT 'NAME OF OUT SOURCING SYSTEM',
    `description` VARCHAR(255) DEFAULT NULL COMMENT 'SYSTEM DESC',
    `system_url` VARCHAR (100) NOT NULL COMMENT 'SYSTEM VISIT URL',
    `app_id` VARCHAR(45) NOT NULL COMMENT 'APP ID',
    `app_key` VARCHAR(255) NOT NULL COMMENT 'APP KEY',
    `app_secret` VARCHAR(255) NOT NULL COMMENT 'APP SECRET',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '1=DELETED, 0=NOT DELETED',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED TIME',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED TIME',
    -- KEYS
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='EXTERNAL SYSTEM';